# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/XILINX/Projects/ML_linear_regression/linear_regression_new/linear_regression/src/linear_regression_top/ip/linear_regression_top_data_proc_0_0/linear_regression_top_data_proc_0_0.xci
# IP: The module: 'linear_regression_top_data_proc_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: e:/XILINX/Projects/ML_linear_regression/linear_regression_new/linear_regression/src/linear_regression_top/ip/linear_regression_top_data_proc_0_0/src/c_shift_ram_0/c_shift_ram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c_shift_ram_0 || ORIG_REF_NAME==c_shift_ram_0} -quiet] -quiet

# IP: e:/XILINX/Projects/ML_linear_regression/linear_regression_new/linear_regression/src/linear_regression_top/ip/linear_regression_top_data_proc_0_0/src/dsp48_multiplier/dsp48_multiplier.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dsp48_multiplier || ORIG_REF_NAME==dsp48_multiplier} -quiet] -quiet

# IP: e:/XILINX/Projects/ML_linear_regression/linear_regression_new/linear_regression/src/linear_regression_top/ip/linear_regression_top_data_proc_0_0/src/dsp48_multiplier_1/dsp48_multiplier_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dsp48_multiplier_1 || ORIG_REF_NAME==dsp48_multiplier_1} -quiet] -quiet

# IP: e:/XILINX/Projects/ML_linear_regression/linear_regression_new/linear_regression/src/linear_regression_top/ip/linear_regression_top_data_proc_0_0/src/c_shift_ram_1/c_shift_ram_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c_shift_ram_1 || ORIG_REF_NAME==c_shift_ram_1} -quiet] -quiet

# IP: E:/XILINX/Projects/ML_linear_regression/linear_regression_new/linear_regression/src/linear_regression_top/ip/linear_regression_top_data_proc_0_0/linear_regression_top_data_proc_0_0.xci
# IP: The module: 'linear_regression_top_data_proc_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: e:/XILINX/Projects/ML_linear_regression/linear_regression_new/linear_regression/src/linear_regression_top/ip/linear_regression_top_data_proc_0_0/src/c_shift_ram_0/c_shift_ram_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c_shift_ram_0 || ORIG_REF_NAME==c_shift_ram_0} -quiet] -quiet

# IP: e:/XILINX/Projects/ML_linear_regression/linear_regression_new/linear_regression/src/linear_regression_top/ip/linear_regression_top_data_proc_0_0/src/dsp48_multiplier/dsp48_multiplier.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dsp48_multiplier || ORIG_REF_NAME==dsp48_multiplier} -quiet] -quiet

# IP: e:/XILINX/Projects/ML_linear_regression/linear_regression_new/linear_regression/src/linear_regression_top/ip/linear_regression_top_data_proc_0_0/src/dsp48_multiplier_1/dsp48_multiplier_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dsp48_multiplier_1 || ORIG_REF_NAME==dsp48_multiplier_1} -quiet] -quiet

# IP: e:/XILINX/Projects/ML_linear_regression/linear_regression_new/linear_regression/src/linear_regression_top/ip/linear_regression_top_data_proc_0_0/src/c_shift_ram_1/c_shift_ram_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c_shift_ram_1 || ORIG_REF_NAME==c_shift_ram_1} -quiet] -quiet
