# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/XILINX/Projects/ML_linear_regression/linear_regression_new/linear_regression/linear_regression.srcs/sources_1/ip/c_shift_ram_1/c_shift_ram_1.xci
# IP: The module: 'c_shift_ram_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/XILINX/Projects/ML_linear_regression/linear_regression_new/linear_regression/linear_regression.srcs/sources_1/ip/c_shift_ram_1/c_shift_ram_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'c_shift_ram_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: e:/XILINX/Projects/ML_linear_regression/linear_regression_new/linear_regression/linear_regression.srcs/sources_1/ip/c_shift_ram_1/c_shift_ram_1.xci
# IP: The module: 'c_shift_ram_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/XILINX/Projects/ML_linear_regression/linear_regression_new/linear_regression/linear_regression.srcs/sources_1/ip/c_shift_ram_1/c_shift_ram_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'c_shift_ram_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
